version: "3.7"

services:
  api:
    build: .
    container_name: api
    ports:
      - 9999:80
    volumes:
      - ./:/go/src/github.com/tutabeier/golang-skeleton
    networks:
      main:
        aliases:
          - tracing
          - monitoring

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 16686:16686
    networks:
      main:
        aliases:
          - tracing

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      main:
        aliases:
          - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      main:
        aliases:
          - monitoring

networks:
  main: